server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        defaultRabbit: # 表示定义的名称，用于于binding整合
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: atguiguA


# Eureka配置
eureka:
  client:
    #是否将自己注册进入eurekaserver,默认值为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认值为true;
    #单节点的情况下无所谓，集群必须设置为true，才能配置ribbon实现负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #      defaultZone: http://localhost:7001/eureka
      #集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

  # 主机名称：服务名称修改 防止eureka界面显示主机名称
  instance:
    #eureka界面显示服务名
    hostname: gateway-9527.com
    #是否显示访问的IP地址
    prefer-ip-address: true
    #eureka客户端像服务端发送心跳的时间间隔 单位是秒（默认值为30秒）
    lease-renewal-interval-in-seconds: 1
    #eureka服务端收到最后一次心跳等待时间上限，单位是秒（默认值为90秒） 超时将剔除服务
    lease-expiration-duration-in-seconds: 2
