#80表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80

#服务别名---注册zookeeper到注册中心的名称
spring:
  application:
    name: cloud-consumer-order
  cloud:
    zookeeper:
      #zookeeper一个机器的Ip地址
      connect-string: 192.168.1.101:2181


